config/routes.rb
Shop::Application.routes.draw do
  
  resources :itemstables
  resources :items

  devise_for  :users,
              :skip => [:registrations, :confirmations]
  
  scope "api" do
    resources :users
    resources :orders
  end
  match "users/filter" => "users#filter"
  
  root to: "users#index"

  match "orders" => "orders#index"

end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :credit_card_number, :credit_card_type, :cvv2, :date_of_ordering, :delivery_date, :expiry_date, :issue_number, :max_discount, :order_number, :pref_delivery_date, :role, :start_date, :status, :total_num_of_items, :total_price
  has_one :user
  has_many :itemstables  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.page params[:page]

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/new
  # GET /orders/new.json
  def new
    @order = Order.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find(params[:id])
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(params[:order])

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render json: @order, status: :created, location: @order }
      else
        format.html { render action: "new" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /orders/1
  # PUT /orders/1.json
  def update
    @order = Order.find(params[:id])

    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :order_number %><br />
    <%= f.text_field :order_number %>
  </div>
  <div class="field">
    <%= f.label :total_price %><br />
    <%= f.text_field :total_price %>
  </div>
  <div class="field">
    <%= f.label :total_num_of_items %><br />
    <%= f.number_field :total_num_of_items %>
  </div>
  <div class="field">
    <%= f.label :max_discount %><br />
    <%= f.text_field :max_discount %>
  </div>
  <div class="field">
    <%= f.label :delivery_date %><br />
    <%= f.date_select :delivery_date %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :role %><br />
    <%= f.text_field :role %>
  </div>
  <div class="field">
    <%= f.label :date_of_ordering %><br />
    <%= f.date_select :date_of_ordering %>
  </div>
  <div class="field">
    <%= f.label :pref_delivery_date %><br />
    <%= f.date_select :pref_delivery_date %>
  </div>
  <div class="field">
    <%= f.label :credit_card_type %><br />
    <%= f.text_field :credit_card_type %>
  </div>
  <div class="field">
    <%= f.label :credit_card_number %><br />
    <%= f.text_field :credit_card_number %>
  </div>
  <div class="field">
    <%= f.label :cvv2 %><br />
    <%= f.text_field :cvv2 %>
  </div>
  <div class="field">
    <%= f.label :expiry_date %><br />
    <%= f.date_select :expiry_date %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :issue_number %><br />
    <%= f.text_field :issue_number %>
  </div>
  <div class="field">
    <%= f.label :itemstable %><br />
    <%= f.text_field :itemstable %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<%= content_tag "div", "Wait pls...", id: "orders", data: {orders: @orders.to_json} %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Order number:</b>
  <%= @order.order_number %>
</p>

<p>
  <b>Total price:</b>
  <%= @order.total_price %>
</p>

<p>
  <b>Total num of items:</b>
  <%= @order.total_num_of_items %>
</p>

<p>
  <b>Max discount:</b>
  <%= @order.max_discount %>
</p>

<p>
  <b>Delivery date:</b>
  <%= @order.delivery_date %>
</p>

<p>
  <b>Status:</b>
  <%= @order.status %>
</p>

<p>
  <b>User:</b>
  <%= @order.user %>
</p>

<p>
  <b>Role:</b>
  <%= @order.role %>
</p>

<p>
  <b>Date of ordering:</b>
  <%= @order.date_of_ordering %>
</p>

<p>
  <b>Pref delivery date:</b>
  <%= @order.pref_delivery_date %>
</p>

<p>
  <b>Credit card type:</b>
  <%= @order.credit_card_type %>
</p>

<p>
  <b>Credit card number:</b>
  <%= @order.credit_card_number %>
</p>

<p>
  <b>Cvv2:</b>
  <%= @order.cvv2 %>
</p>

<p>
  <b>Expiry date:</b>
  <%= @order.expiry_date %>
</p>

<p>
  <b>Start date:</b>
  <%= @order.start_date %>
</p>

<p>
  <b>Issue number:</b>
  <%= @order.issue_number %>
</p>

<p>
  <b>Itemstable:</b>
  <%= @order.itemstable %>
</p>


<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>