config/routes.rb
Shop::Application.routes.draw do
  
  resources :itemstables
  resources :items

  devise_for  :users,
              :skip => [:registrations, :confirmations]
  
  scope "api" do
    resources :users
    resources :orders
  end
  match "users/filter" => "users#filter"
  
  root to: "users#index"

  match "orders" => "orders#index"

end

app/controllers/itemstables_controller.rb
class ItemstablesController < ApplicationController
  # GET /itemstables
  # GET /itemstables.json
  def index
    @itemstables = Itemstable.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @itemstables }
    end
  end

  # GET /itemstables/1
  # GET /itemstables/1.json
  def show
    @itemstable = Itemstable.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @itemstable }
    end
  end

  # GET /itemstables/new
  # GET /itemstables/new.json
  def new
    @itemstable = Itemstable.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @itemstable }
    end
  end

  # GET /itemstables/1/edit
  def edit
    @itemstable = Itemstable.find(params[:id])
  end

  # POST /itemstables
  # POST /itemstables.json
  def create
    @itemstable = Itemstable.new(params[:itemstable])

    respond_to do |format|
      if @itemstable.save
        format.html { redirect_to @itemstable, notice: 'Itemstable was successfully created.' }
        format.json { render json: @itemstable, status: :created, location: @itemstable }
      else
        format.html { render action: "new" }
        format.json { render json: @itemstable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /itemstables/1
  # PUT /itemstables/1.json
  def update
    @itemstable = Itemstable.find(params[:id])

    respond_to do |format|
      if @itemstable.update_attributes(params[:itemstable])
        format.html { redirect_to @itemstable, notice: 'Itemstable was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @itemstable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /itemstables/1
  # DELETE /itemstables/1.json
  def destroy
    @itemstable = Itemstable.find(params[:id])
    @itemstable.destroy

    respond_to do |format|
      format.html { redirect_to itemstables_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/itemstables_helper.rb
module ItemstablesHelper
end

app/views/itemstables/_form.html.erb
<%= form_for(@itemstable) do |f| %>
  <% if @itemstable.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@itemstable.errors.count, "error") %> prohibited this itemstable from being saved:</h2>

      <ul>
      <% @itemstable.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :item %><br />
    <%= f.text_field :item %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :price_per_line %><br />
    <%= f.text_field :price_per_line %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/itemstables/edit.html.erb
<h1>Editing itemstable</h1>

<%= render 'form' %>

<%= link_to 'Show', @itemstable %> |
<%= link_to 'Back', itemstables_path %>

app/views/itemstables/index.html.erb
<h1>Listing itemstables</h1>

<table>
  <tr>
    <th>Item</th>
    <th>Quantity</th>
    <th>Price per line</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @itemstables.each do |itemstable| %>
  <tr>
    <td><%= itemstable.item %></td>
    <td><%= itemstable.quantity %></td>
    <td><%= itemstable.price_per_line %></td>
    <td><%= link_to 'Show', itemstable %></td>
    <td><%= link_to 'Edit', edit_itemstable_path(itemstable) %></td>
    <td><%= link_to 'Destroy', itemstable, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Itemstable', new_itemstable_path %>

app/views/itemstables/new.html.erb
<h1>New itemstable</h1>

<%= render 'form' %>

<%= link_to 'Back', itemstables_path %>

app/views/itemstables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Item:</b>
  <%= @itemstable.item %>
</p>

<p>
  <b>Quantity:</b>
  <%= @itemstable.quantity %>
</p>

<p>
  <b>Price per line:</b>
  <%= @itemstable.price_per_line %>
</p>


<%= link_to 'Edit', edit_itemstable_path(@itemstable) %> |
<%= link_to 'Back', itemstables_path %>